language: python
sudo: false
python:
  - '2.7'
install:
  - pip wheel phonenumbers regex coverage -w $HOME/wheelhouse --find-links $HOME/wheelhouse
  - pip install phonenumbers regex coverage --use-wheel --no-index --find-links $HOME/wheelhouse
  - pip install beautifulsoup4 requests websocket-client pytest
script:
  - python -W default::Warning -m pytest test
branches:
  only:
    - master
    - travis
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/wheelhouse
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
