language: python
sudo: false
python:
  - '2.7'
install:
  - pip install beautifulsoup4 requests websocket-client coverage pytest phonenumbers
script:
  - python -W default::Warning -m pytest test
branches:
  only:
    - master
    - travis
cache:
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

